dist: trusty

language: node_js
node_js:
  - "10"

addons:
  apt:
    packages:
      - libsecret-1-dev
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN

env:
  global:
    - TEST_RESULTS_FILE=test-results.xml

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build:debug
  - npm test  
  - npm run lint -- -o tslint-report.json --format json
  - sonar-scanner

before_deploy:
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - npm run package

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    name: "Version $PACKAGE_VERSION"
    on:
      tags: true
  - provider: script  
    script: npm run publish -- -p $VSCE_TOKEN --packagePath *.vsix
    skip_cleanup: true
    on:
      tags: true