dist: trusty

language: node_js
node_js:
  - "10"

addons:
  apt:
    packages:
      - libsecret-1-dev
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN

env:
  - TEST_RESULTS_FILE=test-results.xml

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build:debug
  - npm test  
  - npm run lint -- -o tslint-report.json --format json
  - sonar-scanner
  - npm run package
