dist: trusty

language: node_js
node_js:
  - "10"

addons:
  apt:
    packages:
      - libsecret-1-dev

# env:
#   - TEST_RESULTS_FILE=test-results.xml

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build:debug
  - npm test
  - npm run clean
  - npm run build
  - npm run package