# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/install-packages
      - restore_cache:
          keys: 
            - vscode
      - run: npm test
      - save_cache:
          key: vscode
          paths:
            - ".vscode"
      - store_test_results:
          path: junit.xml
      - run: npm run lint -- -o eslint-report.json --format json
      - sonarcloud/scan
  publish:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Publish extension on VSCode Marketplace"
          command: |
            echo $(node -p "require('./package.json').version") > .version
            npm run publish -- -p $VSCE_TOKEN --packagePath *.vsix
      - persist_to_workspace:
          root: .
          paths: [ *.vsix, .version ]
  github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/.version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ./artifacts/vlocode-${VERSION}.vsix

workflows:
  validate: 
    jobs:
      - build-and-test:
          context: sonarcloud
  publish: 
    jobs:
      - publish:
          context: vsce
          filters: &filters-publish
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - github-release:
          context: github
          requires:
            - publish
          filters:
            <<: *filters-publish