# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7
  sonarcloud: sonarsource/sonarcloud@1.0.2

commands: 
  checkout_install:
    steps:
      - checkout
      - restore_cache:
          keys: 
            - npm
      - run: npm install
      - save_cache:
          key: npm
          paths:
            - "node_modules"
            - "~/.npm"
  vsce_test:
    steps:
      - restore_cache:
          keys: 
            - vscode
      - run: npm test
      - save_cache:
          key: vscode
          paths:
            - ".vscode"
            - ".vscode-test"    
      - store_test_results:
          path: test-results

jobs:
  build-and-test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout_install
      - vsce_test
      - run: npm run lint -- -o eslint-report.json --format json
      - sonarcloud/scan
  publish-vsc-extension:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout_install
      - run:
          name: "Publish extension on VSCode Marketplace"
          command: |
            echo $(node -p "require('./package.json').version") > .version
            npm run package
      - persist_to_workspace:
          root: .
          paths: [ "*.vsix", ".version" ]
  publish-npm-packages:
    docker:
      - image: circleci/node:16
    steps:
      - checkout_install
      - run:
          name: "Build packages"
          command: npm run build --workspaces
      - run:
          name: "Publish NPM packages"
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            npm publish --workspaces --dry-run
  github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/.version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ./artifacts/vlocode-${VERSION}.vsix

workflows:
  main: 
    jobs:
      - build-and-test:
          context: sonarcloud
      - publish-vsc-extension:
          context: vsce
          requires:
            - build-and-test
      - publish-npm-packages:
          context: npm
          requires:
            - build-and-test
      - github-release:
          context: github
          requires:
            - publish-vsc-extension
            - publish-npm-packages