name: Test & Validate

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':0'

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Start Xvfb
      run: sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
    # Building and linting
    - run: npm ci
    - run: npm test
    - run: npm run lint
    # Updates notes for next release
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # SonarQube quality scan
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
