name: Vlocode CI

on:
  workflow_dispatch: {}
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':0'

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: 'xhost local:'
    - run: npm test
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
