name: Publish Extension

on:
  workflow_dispatch: {}

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'  
    # Install deps, bump version and build the package
    - run: npm ci
    - run: npm run bump
    - name: get-version
      run: export PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - run: npm run build
    - run: npm run package  
    # Create tag so it can be publihsed
    - name: tag
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "v${{ env.PACKAGE_VERSION }}"
    # Create the release
    - name: release
      uses: ncipollo/release-action@v1
      with:
        name: "Version ${{ env.PACKAGE_VERSION }}"
        artifact: '*.vsix'
        artifactErrorsFailBuild: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v${{ env.PACKAGE_VERSION }}"
