name: Create release

on:
  workflow_dispatch:     
    inputs:
     bumpVersion:
        description: 'Bump Version'     
        required: true
        default: 'true'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'  
    # Install deps, bump version and build the package
    - run: npm ci
    - name: Bump version
      if: github.event.inputs.bumpVersion == 'true'
      run: npm run bump
    - name: Build
      run: | 
        npm ci
        echo "PACKAGE_VERSION="$(node -p "require('./package.json').version") >> $GITHUB_ENV
    - run: echo ${{ env.PACKAGE_VERSION }}
    # Create tag so it can be publihsed
    - name: Commit Tag 
      if: github.event.inputs.bumpVersion == 'true'
      run: |
        git config --global user.name '${{ env.GITHUB_ACTOR }}'
        git config --global user.email 'curlybracket-nl@users.noreply.github.com'
        git commit -am "CI: bumping version to v${{ env.PACKAGE_VERSION }}"
        git tag -fa "v${{ env.PACKAGE_VERSION }}"
        git push --tags
    # Create the release
    - name: Draft release
      uses: ncipollo/release-action@v1
      with:
        name: "Version ${{ env.PACKAGE_VERSION }}"
        artifact: '*.vsix'
        artifactErrorsFailBuild: true
        allowUpdates: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "v${{ env.PACKAGE_VERSION }}"
